[package]
name = "ewens-sampler"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.49", features = ["derive"] }
color-eyre = "0.6.5"
env_logger = "0.11.8"
indicatif = "0.18.0"
itertools = "0.14.0"
log = "0.4.28"
rand = { version = "0.9.2", features = ["small_rng"] }
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "sampling"
harness = false
